"""Pursuit skill workspace — scaffold vault artifacts + deterministic capture brief."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .deterministic.opportunity_score import enrich_opportunity_row
from .deterministic.pursuit_paths import pursuit_brief_path, pursuit_slug
from .user_data import read_knowledge_file, write_knowledge_file

WORKSPACE_SKILLS = [
    {
        "id": "capture-brief",
        "name": "Capture Brief",
        "status": "partial",
        "use_when": "Lightweight pursuit snapshot from USASpending row + vault context",
    },
    {
        "id": "sam-monitor-builder",
        "name": "SAM Monitor Builder",
        "status": "partial",
        "use_when": "Save a SAM.gov keyword search for this contract cycle",
    },
]


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _enriched_row(item: Dict[str, Any], naics: str, brain_names: Optional[List[str]] = None) -> Dict[str, Any]:
    return enrich_opportunity_row(
        item,
        naics=naics,
        brain_names=brain_names or [],
        existing_monitor_keys=set(),
    )


def get_workspace_meta(
    item: Dict[str, Any],
    naics: str = "561210",
    *,
    brain_names: Optional[List[str]] = None,
) -> Dict[str, Any]:
    row = _enriched_row(item, naics, brain_names)
    slug = row.get("pursuit_slug") or pursuit_slug(item)
    brief_rel = row.get("pursuit_brief_path") or pursuit_brief_path(slug)
    brief = read_knowledge_file(brief_rel)
    return {
        "slug": slug,
        "brief_path": brief_rel,
        "brief_exists": bool(brief),
        "brief_bytes": brief.get("size", 0) if brief else 0,
        "row": row,
        "skills": WORKSPACE_SKILLS,
        "vault_root": f"pursuits/{slug}",
    }


def _signal_lines(signals: List[str]) -> str:
    if not signals:
        return "- (none in current slice)"
    return "\n".join(f"- {s}" for s in signals)


def build_capture_brief_markdown(
    row: Dict[str, Any],
    naics: str,
    *,
    brain_names: Optional[List[str]] = None,
) -> str:
    slug = row.get("pursuit_slug") or pursuit_slug(row)
    recipient = row.get("recipient") or "Unknown incumbent"
    agency = row.get("agency") or "Unknown agency"
    end = row.get("end_date") or "—"
    months = row.get("months_to_end")
    oblig_m = row.get("obligation_millions")
    if oblig_m is None:
        oblig_m = round((row.get("obligation") or 0) / 1e6, 2)
    tier = row.get("tier_label") or row.get("combo_tier") or "track"
    score = row.get("display_score") or row.get("combo_score") or 0
    award_key = row.get("award_key") or ""
    signals = row.get("signals") or []
    sam_kw = row.get("suggested_sam_keywords") or ""
    brain_note = ", ".join(brain_names[:5]) if brain_names else "none"

    return f"""---
id: pursuit-{slug}
type: pursuit-brief
slug: {slug}
naics: {naics}
award_key: "{award_key}"
updated: {_utc_now()}
tags: [capture, recompete, pursuit]
---

# Capture Brief — {recipient}

## Contract snapshot
| Field | Value |
|-------|-------|
| **Incumbent (holder)** | {recipient} |
| **Customer agency** | {agency} |
| **Contract ends** | {end} ({months} months left) |
| **Obligated value** | ${oblig_m}M |
| **Priority** | {tier} (score {score}) |

## Why flagged
{_signal_lines(signals)}

## Suggested SAM.gov search
`{sam_kw}`

## Vault / brain context
Tracked names in brain: {brain_note}

## Next moves (deterministic)
1. **Track** — add to Pipeline if not already watching this cycle.
2. **Save SAM search** — bookmark keywords above for RFIs / Sources Sought.
3. **Customer** — confirm recompete timing with contracting office if relationship exists.
4. **Competitor** — brief incumbent posture; add to vault if missing.

## Citations
- USASpending expiring award `{award_key or 'n/a'}` · NAICS {naics}
- Generated by capture-brief skill (deterministic) · {_utc_now()}
"""


def scaffold_capture_brief(
    item: Dict[str, Any],
    naics: str = "561210",
    *,
    brain_names: Optional[List[str]] = None,
    overwrite: bool = False,
) -> Dict[str, Any]:
    row = _enriched_row(item, naics, brain_names)
    slug = row.get("pursuit_slug") or pursuit_slug(item)
    brief_rel = pursuit_brief_path(slug)

    existing = read_knowledge_file(brief_rel)
    if existing and not overwrite:
        return {
            "ok": True,
            "created": False,
            "path": brief_rel,
            "slug": slug,
            "bytes": existing.get("size", 0),
            "message": "Brief already exists",
        }

    content = build_capture_brief_markdown(row, naics, brain_names=brain_names)
    written = write_knowledge_file(brief_rel, content)
    if not written:
        return {"ok": False, "error": "failed to write brief", "path": brief_rel}

    return {
        "ok": True,
        "created": True,
        "path": brief_rel,
        "slug": slug,
        "bytes": len(content),
        "content_preview": content[:400],
    }


def run_pursuit_skill(
    skill_id: str,
    item: Dict[str, Any],
    naics: str = "561210",
    *,
    brain_names: Optional[List[str]] = None,
    use_llm: bool = False,
) -> Dict[str, Any]:
    if skill_id == "capture-brief":
        result = scaffold_capture_brief(
            item, naics, brain_names=brain_names, overwrite=True
        )
        result["skill_id"] = skill_id
        result["used_llm"] = False
        return result

    if skill_id == "sam-monitor-builder":
        from .deterministic.sam_monitor import build_monitor_entry
        from .user_data import add_to_pipeline

        entry = build_monitor_entry(item, naics, source="workspace-skill")
        saved = add_to_pipeline(entry)
        return {
            "ok": True,
            "skill_id": skill_id,
            "pipeline_entry": entry,
            "accumulators": saved,
            "used_llm": use_llm,
        }

    return {"ok": False, "error": f"unknown skill: {skill_id}"}