"""Shared skill IDs — avoids circular imports between router and invoke service."""

RUNNABLE_SKILL_IDS = frozenset({
    "capture-brief",
    "sam-scan",
    "competitive-snapshot",
    "competitive-battlecard",
    "sam-monitor-builder",
    "competitive-intel",
    "teaming-finder",
    "vault-lint",
    "vault-index-rebuild",
    "vault-synthesize",
    "compliance-auditor",
    "ptw-analysis",
    "pursuit-kickoff",
    "proposal-generator",
    "subcontractor-sow-builder",
    "huashu-design",
    "value-propositions",
    "positioning",
    "competitor-profiling",
    "renderers",
    "rfp-reverse-engineer",
    "oci-sweeper",
    "ot-prototype-strategist",
    "igce-builder-ffp",
    "igce-builder-lh-tm",
    "igce-builder-cr",
    "data-analyzer",
})

PURSUIT_SKILLS = frozenset({
    "capture-brief",
    "sam-scan",
    "competitive-snapshot",
    "competitive-battlecard",
    "sam-monitor-builder",
    "competitive-intel",
    "teaming-finder",
    "compliance-auditor",
    "vault-synthesize",
    "ptw-analysis",
    "pursuit-kickoff",
    "proposal-generator",
    "subcontractor-sow-builder",
    "huashu-design",
    "value-propositions",
    "positioning",
    "competitor-profiling",
    "rfp-reverse-engineer",
    "oci-sweeper",
    "ot-prototype-strategist",
    "igce-builder-ffp",
    "igce-builder-lh-tm",
    "igce-builder-cr",
    "data-analyzer",
})

MARKETING_SKILL_IDS = frozenset({
    "value-propositions",
    "positioning",
    "competitor-profiling",
})